### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by trusktr** [qunxyz/meteor-browserify#1]
The usage says to install it. But how do you use it? Can you give a small practical example? Thanks!

**Comment by qunxyz** [comment]
trusktr, check this project: https://github.com/island205/browserify-loader
I just make it as a meteor package

**Comment by trusktr** [comment]
Oh, I see, so we have to use browserify our selves to create a bundle, then we can place it in the public folder, then we use this plugin to load the bundle? EDIT: Yeah. :)
